-- Sample data for job platform
-- This script adds sample users and job offers for testing

-- Insert sample users (assuming they don't exist)
INSERT IGNORE INTO users (id, name, email, password, role, active) VALUES
(1, 'John Doe', 'john.doe@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'OFFERER', true),
(2, 'Jane Smith', 'jane.smith@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'OFFERER', true),
(3, 'Mike Johnson', 'mike.johnson@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'OFFERER', true),
(4, 'Sarah Wilson', 'sarah.wilson@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'SEEKER', true),
(5, 'Admin User', 'admin@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'ADMIN', true);

-- Insert sample job offers with different dates
INSERT IGNORE INTO job_offers (id, offerer_id, title, company, location, contract_type, domain, skills, salary, duration, deadline, description, raw_text, language, type, created_at, is_active) VALUES
(1, 1, 'Senior Software Engineer', 'TechCorp Inc', 'San Francisco, CA', 'Full-time', 'Software Development', '["Java", "Spring Boot", "Microservices", "AWS"]', '$120,000 - $150,000', 'Permanent', '2024-12-31', 'We are looking for a senior software engineer to join our team...', 'Job Title: Senior Software Engineer\nCompany: TechCorp Inc\nLocation: San Francisco, CA\n\nWe are looking for a senior software engineer to join our team. You will be responsible for developing and maintaining our core platform using Java, Spring Boot, and microservices architecture.\n\nRequirements:\n- 5+ years of Java experience\n- Experience with Spring Boot and microservices\n- Knowledge of AWS cloud services\n- Strong problem-solving skills\n\nContract Type: Full-time\nSalary: $120,000 - $150,000\nDuration: Permanent\nDeadline: 2024-12-31\n\nPlease send your CV to jobs@techcorp.com', 'en', 'Job', '2024-01-15 10:00:00', true),

(2, 2, 'Frontend Developer', 'WebSolutions Ltd', 'New York, NY', 'Full-time', 'Web Development', '["React", "TypeScript", "CSS", "JavaScript"]', '$80,000 - $100,000', 'Permanent', '2024-11-30', 'Join our frontend team to build amazing user experiences...', 'Job Title: Frontend Developer\nCompany: WebSolutions Ltd\nLocation: New York, NY\n\nJoin our frontend team to build amazing user experiences. We are looking for a talented frontend developer with strong React and TypeScript skills.\n\nRequirements:\n- 3+ years of React experience\n- Strong TypeScript knowledge\n- Experience with CSS frameworks\n- Portfolio of previous work\n\nContract Type: Full-time\nSalary: $80,000 - $100,000\nDuration: Permanent\nDeadline: 2024-11-30\n\nApply at careers@websolutions.com', 'en', 'Job', '2024-02-20 14:30:00', true),

(3, 3, 'Data Scientist Intern', 'DataTech Corp', 'Remote', 'Internship', 'Data Science', '["Python", "Machine Learning", "SQL", "Statistics"]', '$3,000/month', '6 months', '2024-10-15', 'Exciting internship opportunity in data science...', 'Job Title: Data Scientist Intern\nCompany: DataTech Corp\nLocation: Remote\n\nExciting internship opportunity in data science. Work on real-world projects and learn from experienced data scientists.\n\nRequirements:\n- Currently enrolled in Computer Science or related field\n- Basic Python knowledge\n- Interest in machine learning\n- Strong analytical thinking\n\nContract Type: Internship\nSalary: $3,000/month\nDuration: 6 months\nDeadline: 2024-10-15\n\nSend applications to internships@datatech.com', 'en', 'Internship', '2024-03-10 09:15:00', true),

(4, 1, 'DevOps Engineer', 'CloudTech Systems', 'Austin, TX', 'Full-time', 'DevOps', '["Docker", "Kubernetes", "AWS", "CI/CD"]', '$110,000 - $130,000', 'Permanent', '2024-12-15', 'Looking for a DevOps engineer to manage our cloud infrastructure...', 'Job Title: DevOps Engineer\nCompany: CloudTech Systems\nLocation: Austin, TX\n\nLooking for a DevOps engineer to manage our cloud infrastructure and improve our deployment processes.\n\nRequirements:\n- 4+ years of DevOps experience\n- Strong knowledge of Docker and Kubernetes\n- AWS certification preferred\n- Experience with CI/CD pipelines\n\nContract Type: Full-time\nSalary: $110,000 - $130,000\nDuration: Permanent\nDeadline: 2024-12-15\n\nContact: devops@cloudtech.com', 'en', 'Job', '2024-04-05 16:45:00', true),

(5, 2, 'UI/UX Designer', 'Creative Agency', 'Los Angeles, CA', 'Part-time', 'Design', '["Figma", "Adobe Creative Suite", "User Research", "Prototyping"]', '$60,000 - $80,000', '12 months', '2024-09-30', 'Join our creative team as a UI/UX designer...', 'Job Title: UI/UX Designer\nCompany: Creative Agency\nLocation: Los Angeles, CA\n\nJoin our creative team as a UI/UX designer. Work on exciting projects for various clients and help create beautiful, user-friendly interfaces.\n\nRequirements:\n- 2+ years of UI/UX design experience\n- Proficiency in Figma and Adobe Creative Suite\n- Strong portfolio\n- Understanding of user research methods\n\nContract Type: Part-time\nSalary: $60,000 - $80,000\nDuration: 12 months\nDeadline: 2024-09-30\n\nApply: design@creativeagency.com', 'en', 'Job', '2024-05-12 11:20:00', true),

(6, 3, 'Backend Developer', 'StartupXYZ', 'Seattle, WA', 'Full-time', 'Software Development', '["Node.js", "Express", "MongoDB", "REST APIs"]', '$90,000 - $110,000', 'Permanent', '2024-11-20', 'Fast-growing startup looking for a backend developer...', 'Job Title: Backend Developer\nCompany: StartupXYZ\nLocation: Seattle, WA\n\nFast-growing startup looking for a backend developer to help build our platform. Work in a dynamic environment with cutting-edge technologies.\n\nRequirements:\n- 3+ years of Node.js experience\n- Strong knowledge of Express.js\n- Experience with MongoDB\n- REST API development skills\n\nContract Type: Full-time\nSalary: $90,000 - $110,000\nDuration: Permanent\nDeadline: 2024-11-20\n\nEmail: careers@startupxyz.com', 'en', 'Job', '2024-06-18 13:10:00', true),

(7, 1, 'Mobile App Developer', 'AppTech Solutions', 'Chicago, IL', 'Contract', 'Mobile Development', '["React Native", "iOS", "Android", "JavaScript"]', '$70/hour', '6 months', '2024-10-31', 'Contract position for mobile app development...', 'Job Title: Mobile App Developer\nCompany: AppTech Solutions\nLocation: Chicago, IL\n\nContract position for mobile app development. Work on our flagship mobile application using React Native.\n\nRequirements:\n- 2+ years of React Native experience\n- iOS and Android development knowledge\n- Strong JavaScript skills\n- Previous mobile app portfolio\n\nContract Type: Contract\nSalary: $70/hour\nDuration: 6 months\nDeadline: 2024-10-31\n\nContact: mobile@apptech.com', 'en', 'Job', '2024-07-25 08:30:00', true),

(8, 2, 'QA Engineer', 'QualityAssurance Inc', 'Boston, MA', 'Full-time', 'Quality Assurance', '["Selenium", "Jest", "Test Automation", "Bug Tracking"]', '$75,000 - $95,000', 'Permanent', '2024-12-01', 'Join our QA team to ensure software quality...', 'Job Title: QA Engineer\nCompany: QualityAssurance Inc\nLocation: Boston, MA\n\nJoin our QA team to ensure software quality. You will be responsible for testing our applications and improving our testing processes.\n\nRequirements:\n- 3+ years of QA experience\n- Experience with Selenium and Jest\n- Knowledge of test automation\n- Attention to detail\n\nContract Type: Full-time\nSalary: $75,000 - $95,000\nDuration: Permanent\nDeadline: 2024-12-01\n\nApply: qa@qualityassurance.com', 'en', 'Job', '2024-08-14 15:45:00', true),

(9, 3, 'Cybersecurity Analyst', 'SecureTech', 'Washington, DC', 'Full-time', 'Cybersecurity', '["Security Analysis", "Penetration Testing", "SIEM", "Risk Assessment"]', '$95,000 - $115,000', 'Permanent', '2024-11-10', 'Protect our systems from cyber threats...', 'Job Title: Cybersecurity Analyst\nCompany: SecureTech\nLocation: Washington, DC\n\nProtect our systems from cyber threats. Join our security team to monitor, analyze, and respond to security incidents.\n\nRequirements:\n- 4+ years of cybersecurity experience\n- Knowledge of penetration testing\n- SIEM experience\n- Security certifications preferred\n\nContract Type: Full-time\nSalary: $95,000 - $115,000\nDuration: Permanent\nDeadline: 2024-11-10\n\nEmail: security@securetech.com', 'en', 'Job', '2024-09-02 12:00:00', true),

(10, 1, 'Product Manager', 'ProductCo', 'San Diego, CA', 'Full-time', 'Product Management', '["Product Strategy", "Agile", "User Stories", "Analytics"]', '$100,000 - $120,000', 'Permanent', '2024-10-25', 'Lead product development and strategy...', 'Job Title: Product Manager\nCompany: ProductCo\nLocation: San Diego, CA\n\nLead product development and strategy. Work with cross-functional teams to deliver amazing products that users love.\n\nRequirements:\n- 5+ years of product management experience\n- Strong analytical skills\n- Experience with Agile methodologies\n- User-focused mindset\n\nContract Type: Full-time\nSalary: $100,000 - $120,000\nDuration: Permanent\nDeadline: 2024-10-25\n\nContact: product@productco.com', 'en', 'Job', '2024-09-20 10:15:00', true);

-- Insert some sample applications for testing
INSERT IGNORE INTO applications (id, seeker_id, job_offer_id, status, cover_letter, resume_url, created_at) VALUES
(1, 4, 1, 'PENDING', 'I am very interested in this position...', 'https://example.com/resume1.pdf', '2024-09-25 14:30:00'),
(2, 4, 2, 'ACCEPTED', 'I have extensive experience with React...', 'https://example.com/resume2.pdf', '2024-09-20 09:15:00'),
(3, 4, 3, 'PENDING', 'I am currently studying Computer Science...', 'https://example.com/resume3.pdf', '2024-09-22 16:45:00'),
(4, 4, 4, 'REFUSED', 'I have 5 years of DevOps experience...', 'https://example.com/resume4.pdf', '2024-09-18 11:20:00'),
(5, 4, 5, 'PENDING', 'I am passionate about UI/UX design...', 'https://example.com/resume5.pdf', '2024-09-24 13:10:00');
